import React,{useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {Gamepad2,Users,User,ArrowUpRight,ArrowRight,Search,SlidersHorizontal,X,Check,Plus,Headphones,Globe,ChevronDown,ArrowLeft,Camera,Copy,CheckCheck,Sparkles, Zap, Radio, LogOut, Star, Play as PlayIcon, CalendarDays, MapPin, MoreHorizontal, MessageSquare, UserPlus, Trophy, Heart, ChevronRight} from 'lucide-react';
import './style.css';
import './reference.css';
import {playerImages} from './characters.js';
import Events from './Events.jsx';
import LocationPicker, {LocationLabel} from './LocationPicker.jsx';
import {isValidLocation, isNearby, restoreProfile} from './locations.js';
import {KANSAS_CITY_LOCATION, playerLocations} from './playerArea.js';
const games=['Valorant','Minecraft','Fortnite','League of Legends','Apex Legends','Rocket League','Overwatch 2','Stardew Valley'];
const colors=['#e9d2c8','#ccdccd','#ddcde6','#e8d9b7'];
const photo=(id,width=600)=>`https://images.unsplash.com/${id}?auto=format&fit=crop&w=${width}&q=85`;
const names=['Maya Chen','Alex Rivera','Sofia Martinez','Jordan Lee','Kai Williams','Emma Wilson','Noah Brooks','Zoe Davis','Ethan Park','Luna Thompson','Oliver Reed','Ava Collins','Leo Bennett','Nina Patel','Theo Harris','Ruby Morgan','Finn Walker','Aria Kim','Max Turner','Isla Lewis','Sam Cooper','Mila Scott','Ben Foster','Chloe Adams'];
const profileBios=[
  "I make playlists for everything, including losing ranked ✨ Usually on Valorant with iced coffee and an anime opening stuck in my head. “Believe it!” — Naruto",
  "Built a whole Minecraft kitchen before remembering I needed a bed. I bake banana bread, collect weird mugs, and will absolutely ask to see your pets.",
  "Can practice Spanish with you or spend an hour debating anime endings. Fortnite between study breaks, voice chat optional. My cat usually has something to say.",
  "League since 2016. Support main, midnight ramen enthusiast, and somehow always on my last game for three more games. Send me your favorite song ♡",
  "Valorant, thrift finds, and a suspicious number of houseplants. “Whatever happens, happens.” — Spike Spiegel. Also my explanation for that last whiff.",
  "Minecraft houses: cute. Storage system: a crime scene. Learning Japanese very slowly, rewatching comfort anime very quickly. Down for a watch party ♡",
  "I say “one more Fortnite game” with the confidence of someone who has never checked the time. Fun fact: I can name more Pokémon than countries.",
  "ARAM enjoyer, soup defender, and designated “wait, what happened?” friend. Here for games, yapping, or just sitting in voice with music on.",
  "I spend longer choosing a Valorant skin than choosing dinner. Basketball after class, anime after midnight. “Plus Ultra!” — All Might, before I queue again.",
  "Cozy Minecraft builds and horror movies I watch through my fingers. Send your music recs; my playlist has been the same twelve songs for a month.",
  "Fortnite with friends, terrible puns, and unnecessarily strong opinions about fries. I learn random recipes at 2am and forget them by breakfast.",
  "Nami main with a tea collection that is getting out of hand. Happy to play League or swap anime recs. I will notice if you skip the opening.",
  "Valorant between guitar practice and pretending to finish my anime backlog. “Whatever happens, happens.” — Spike Spiegel. The backlog agrees.",
  "I build little Minecraft bookstores and then spend all my time decorating them. Also into sketching, rainy-day playlists, and talking about absolutely nothing.",
  "Fortnite, Rocket League, and the occasional cooking disaster. I know too much about space and too little about where I left my headphones.",
  "League support who remembers your birthday but forgets to buy wards. Crochet projects everywhere. “Believe it!” — Naruto. The scarf will get finished.",
  "Valorant player, birdwatching beginner. I can identify exactly three birds and will point out all three. Happy to chat or just queue with music.",
  "Minecraft farms, Stardew farms… apparently I just like farming. Learning Japanese, mostly to understand anime jokes without pausing every ten seconds ♡",
  "Fortnite and movie nights. I rate convenience-store snacks like it is a serious job. Ask me about the instant noodles spreadsheet. Yes, it exists.",
  "League, long walks, and a new hobby every other week. “Plus Ultra!” — All Might. Currently applying that energy to learning how to keep basil alive.",
  "I play Valorant and take blurry photos of my dog. Down to trade playlists, talk through your day, or celebrate finally landing a shot.",
  "Minecraft builder with seventeen unfinished houses. I like language swaps, studio Ghibli, and making pancakes that look nothing like the recipe photo.",
  "Fortnite with the mic on, chess with my brain off. I collect fun facts and forget everyone’s names in anime. Tell me something oddly specific about yourself.",
  "League player with a soft spot for support champs and really bad puns. We can queue, vent, share music, or watch an episode that turns into five ♡"
];
const people=names.map((name,i)=>({id:i,name,location:playerLocations[i%playerLocations.length],handle:name.toLowerCase().split(' ')[0]+'plays',...playerImages[i],games:[games[i%4],games[(i+2)%8],games[(i+5)%8]],online:i%4!==2,region:'North America',style:i%3===0?'Competitive':'Casual',bio:profileBios[i],ign:name.split(' ')[0]+'#'+(1000+i),color:colors[i%4]}));
const playerRank=p=>['Platinum','Silver','Immortal','Diamond','Ascendant','Unranked'][(p.id??0)%6];
const playerRole=p=>['Initiator','Controller','Duelist','Sentinel'][(p.id??0)%4];
function FramedAvatar({player,large=false}){return <span className={'framed-avatar '+(large?'large ':'')+'frame-'+((player.id??0)%4)}><img className={player.character?'character-avatar':undefined} src={player.image} alt={player.character?`${player.character} · ${player.name}`:player.name}/><span className="avatar-crown" aria-hidden="true">♛</span><span className="avatar-medal" aria-hidden="true">✦</span><i className={player.online?'online':'away'}/></span>}
const defaultMe={backgroundImage:playerImages[0].backgroundImage,name:'Jamie Parker',handle:'jamie.gg',image:photo('photo-1472099645785-5658abf4ff4e'),bio:'Casual queues, good company. Usually playing after work — always up for one more game.',games:['Valorant','Minecraft','Fortnite'],ign:'jamie#2048',region:'North America',style:'Casual',online:true,location:null};
function App(){
 const [me,setMe]=useState(()=>{try{return restoreProfile(JSON.parse(localStorage.getItem('sq-profile')),defaultMe)}catch{return defaultMe}});
 const [tab,setTab]=useState('Connect'),[selected,setSelected]=useState(null),[search,setSearch]=useState(''),[filter,setFilter]=useState('All games'),[online,setOnline]=useState(false),[style,setStyle]=useState('Any playstyle'),[filterOpen,setFilterOpen]=useState(false),[limit,setLimit]=useState(12),[modal,setModal]=useState(null),[party,setParty]=useState(null),[inviteCandidate,setInviteCandidate]=useState(null),[ready,setReady]=useState(false),[toast,setToast]=useState(''),[onboard,setOnboard]=useState(()=>!localStorage.getItem('sq-onboarded'));
 const [friendIds,setFriendIds]=useState(()=>{try{const saved=JSON.parse(localStorage.getItem('sq-friends'));return Array.isArray(saved)?[...new Set(saved.filter(id=>people.some(p=>p.id===id)))]:[]}catch{return []}});
 useEffect(()=>localStorage.setItem('sq-friends',JSON.stringify(friendIds)),[friendIds]);
 const connect=p=>{if(friendIds.includes(p.id))return;setFriendIds(current=>current.includes(p.id)?current:[...current,p.id]);setToast(`${p.name} added to your friends.`)};
 const disconnect=p=>{setFriendIds(current=>current.filter(id=>id!==p.id));setToast(`${p.name} removed from your connections.`)};
 const sentinel=useRef(null), dialogRef=useRef(null);
 useEffect(()=>{if(!modal)return;const previous=document.activeElement;dialogRef.current?.querySelector('button')?.focus();const handler=e=>{if(e.key==='Escape')setModal(null);if(e.key==='Tab'){const items=dialogRef.current?.querySelectorAll('button:not(:disabled),input,textarea,select');if(!items?.length)return;const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener('keydown',handler);return()=>{document.removeEventListener('keydown',handler);previous?.focus()}},[modal]);
 useEffect(()=>localStorage.setItem('sq-profile',JSON.stringify(me)),[me]);
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),3000);return()=>clearTimeout(t)}},[toast]);
 useEffect(()=>{const o=new IntersectionObserver(e=>{if(e[0].isIntersecting)setLimit(n=>Math.min(n+8,people.length))},{rootMargin:'180px'});if(sentinel.current)o.observe(sentinel.current);return()=>o.disconnect()},[tab,filter,search,selected,me.location]);
 const hasLocation=isValidLocation(me.location);
 const filtered=people.filter(p=>isNearby(KANSAS_CITY_LOCATION,p.location)&&(filter==='All games'||p.games.includes(filter))&&(!online||p.online)&&(style==='Any playstyle'||p.style===style)&&(`${p.name} ${p.games.join(' ')}`.toLowerCase().includes(search.toLowerCase())));
 useEffect(()=>setLimit(12),[me.location,me.games,filter,search,online,style]);
 const switchTab=t=>{setTab(t);setSelected(null);window.scrollTo({top:0,behavior:'smooth'})};
 const invite=p=>{if(party?.members.some(m=>m.player.id===p.id)){setToast('This player is already in your party.');switchTab('Play');return}if(party?.members.length>=5){setToast('Your party is full — six players including you.');switchTab('Play');return}setInviteCandidate(p);switchTab('Play');setModal('party')};
 const openParty=()=>{setInviteCandidate(null);setModal('party')};
 const saveParty=draft=>{setParty(draft);setReady(false);setModal(null);setInviteCandidate(null);setToast(party?'Party updated.':'Party created. Demo invitations are ready.')};
 const acceptInvite=id=>{setParty(current=>({...current,members:current.members.map(m=>m.player.id===id?{...m,status:'joined'}:m)}));setReady(false);setToast('Demo invite accepted!')};
 const leave=()=>{setParty(null);setReady(false);setToast('Party closed. Your next teammate is out there.')};
 return <div className="app"><header className="topbar"><button className="brand" onClick={()=>switchTab('Connect')}><span className="brand-icon"><Gamepad2 size={25}/></span>sidequest<span className="brand-dot">.</span></button><button className="account" onClick={()=>switchTab('Profile')}><span className="online-dot"/> <span>Hey, {me.name.split(' ')[0]}</span><img src={me.image} alt="Your profile"/><ChevronDown size={14}/></button></header>
 <main className="shell">{tab==='Connect'&&!selected?<><section className="hero"><img className="hero-image" src={photo("photo-1542751371-adc38448a05e",1600)} alt="Gaming stations under purple and blue lighting"/><div className="hero-copy"><div className="eyebrow"><span/> YOUR NEXT GREAT TEAM STARTS HERE</div><h1>Find your people.<br/><span>Play your game.</span></h1><p>Same games. Same energy. A whole new party.</p><div className="hero-proof"><div className="avatar-stack">{filtered.slice(0,4).map(p=><img key={p.id} src={p.image} alt=""/>)}</div><span><strong>1.2k+</strong> players finding their next duo <ArrowUpRight size={15}/></span></div>{onboard&&<button className="onboarding-prompt" onClick={()=>setModal('interests')}><Sparkles size={13}/> New here? Pick your games <ArrowRight size={13}/></button>}</div><div className="hero-art"><span className="hero-outline">PLAY<br/>TOGETHER</span><div className="floating-tag tag-one"><span className="online-dot"/> Your next duo is out there</div><div className="floating-tag tag-two"><Zap size={14} fill="currentColor"/> Better together.</div></div></section>
 <section className="discovery-games" aria-label="Discover players by game">{[['Valorant','Competitive queues','V'],['Minecraft','Build something together','▧'],['Fortnite','Drop in with your next duo','F']].map(([g,description,mark],i)=><button key={g} className={'discovery-game discovery-'+i+(filter===g?' selected':'')} aria-pressed={filter===g} onClick={()=>{setFilter(g);setLimit(12)}}><span><strong>{g}</strong><small>{description}</small></span><span className="discovery-symbol" aria-hidden="true">{mark}</span><ArrowRight size={19}/></button>)}</section><div className="content-layout"><section className="profiles-section"><div className="section-head"><div className="title-and-filter"><h2>Find your duo <span>{filtered.length}</span></h2><button className={'filter-button '+(filterOpen?'active':'')} onClick={()=>setFilterOpen(!filterOpen)}><SlidersHorizontal size={15}/> Filters {(online||style!=='Any playstyle')&&<span className="filter-dot"/>}</button></div><label className="search"><Search size={16}/><input placeholder="Find your next teammate" value={search} onChange={e=>{setSearch(e.target.value);setLimit(12)}}/></label></div>
 <div className="connect-location"><span><MapPin size={14}/>Within 50 miles of Kansas City, MO · Demo players</span></div>
 {filterOpen&&<div className="filter-panel"><label><input type="checkbox" checked={online} onChange={e=>setOnline(e.target.checked)}/> Online now</label><select aria-label="Playstyle" value={style} onChange={e=>setStyle(e.target.value)}>{['Any playstyle','Casual','Competitive'].map(s=><option key={s}>{s}</option>)}</select><button onClick={()=>{setOnline(false);setStyle('Any playstyle');setFilter('All games');setSearch('')}}>Reset</button></div>}
 <div className="game-tabs">{['All games',...me.games].map(g=><button key={g} className={filter===g?'chosen':''} onClick={()=>{setFilter(g);setLimit(12)}}>{g==='All games'?<Gamepad2 size={14}/>:<span className={'game-mark '+g.toLowerCase().replaceAll(' ','')}>{g==='Valorant'?'V':g==='Minecraft'?'▧':'F'}</span>}{g}</button>)}</div>
 <div className="profile-grid">{filtered.slice(0,limit).map(p=><article className="profile-card reference-card character-card" key={p.id}><button className="card-profile-link" onClick={()=>{setSelected(p);window.scrollTo({top:0,behavior:'smooth'})}} aria-label={`View ${p.name}'s profile`}/><img className="card-backdrop" src={p.backgroundImage} alt={`${p.backgroundCharacter} from ${p.backgroundGame}`} loading="lazy"/><div className="card-top"><FramedAvatar player={p}/><span className="card-play" aria-hidden="true"><PlayIcon size={22} fill="currentColor"/></span></div><div className="card-info"><h3>{p.name} <span className="identity-badge" aria-label="Player badge">✦</span></h3><LocationLabel location={p.location}/><ConnectButton connected={friendIds.includes(p.id)} onConnect={()=>connect(p)} name={p.name}/><div className="card-rating"><Star size={16} fill="currentColor"/><strong>{p.style}</strong><span>({p.region==='Europe'?'EU':'NA'})</span></div><div className="player-tags"><span>{playerRank(p)}</span><span>{playerRole(p)}</span></div><p className="card-bio">{p.bio}</p>{p.games.filter(g=>me.games.includes(g)).length>1&&<span className="compatibility-badge"><Zap size={13} fill="currentColor"/> Your kind of player</span>}<div className="card-footer"><span className="energy-token"><Zap size={11} fill="currentColor"/></span><strong>{p.games.filter(g=>me.games.includes(g)).length}</strong><span> /Shared games</span></div></div></article>)}</div>{!filtered.length&&<div className="empty-state"><Search/><h3>No nearby teammates found</h3><p>No players match your filters within 50 miles of Kansas City, MO. Try another game or adjust your filters.</p></div>}<div ref={sentinel} className="load-note">{limit<filtered.length?'Finding more of your people…':<><span/> You’re all caught up. More good company soon.</>}</div></section>
 <aside><div className="your-games"><div className="aside-head"><span>YOUR PLAYER CARD</span><button aria-label="Edit your profile" onClick={()=>setModal('edit')}><ArrowUpRight size={17}/></button></div><div className="mini-profile"><img src={me.image} alt=""/><div><h3>{me.name}</h3><LocationLabel location={me.location}/><span><i/> {hasLocation?'Ready to connect':'Set your city to connect'}</span></div></div><div className="divider"/><div className="aside-head"><h4>Your rotation</h4><button aria-label="Edit game interests" onClick={()=>setModal('interests')}><Plus size={16}/></button></div><div className="rotation">{me.games.map((g,i)=><div key={g}><div className={'game-cover cover-'+i}><Gamepad2 size={22}/></div><span>{g}<small>{i===0?'Your main game':'In the rotation'}</small></span></div>)}</div><button className="text-link" onClick={()=>switchTab('Profile')}>View your profile <ArrowRight size={15}/></button></div>
 <div className="party-callout"><span className="callout-icon"><Headphones size={23}/></span><h3>Less solo.<br/>More squad.</h3><p>The best part of gaming?<br/>The people you play with.</p><button onClick={()=>switchTab('Play')}>Start a party <ArrowUpRight size={16}/></button><div className="callout-decoration">✳</div></div><div className="community-note"><span className="online-dot"/> A little kindness goes a long way.<br/><span>Keep it friendly. Keep it fun.</span></div></aside></div>
 {onboard&&<div className="welcome-banner"><Sparkles size={20}/><div><strong>Welcome to your next sidequest.</strong><span> Pick your games to find players with the same interests.</span></div><button onClick={()=>setModal('interests')}>Pick my games <ArrowRight size={14}/></button></div>}</>:tab==='Map'?<Events notify={setToast} connections={people.filter(p=>friendIds.includes(p.id))}/>:tab==='Play'?<section className="play-page">
 <div className="page-heading"><div><div className="eyebrow">GOOD COMPANY IS ONE INVITE AWAY</div><h1>Your party.</h1><p>Pick your game. Bring your people. Up to six, including you.</p></div><div className="party-actions"><button className="primary" onClick={openParty}>{party?'Manage party':'Create a party'} <Plus size={16}/></button>{party&&<button className="secondary" onClick={leave}><LogOut size={16}/> Cancel game</button>}</div></div>
 {party&&<div className="party-session"><div><div className="eyebrow">EVERY INVITE INCLUDES</div><h2><Gamepad2 size={23}/>{party.settings.game}</h2></div><PartyDetails settings={party.settings}/><span className="party-count"><Users size={15}/>{party.members.length+1} / 6 players · {party.members.filter(m=>m.status==='joined').length+1} connected</span></div>}
 <div className={party?'party-board squad-board':'party-board'} style={party?{'--party-columns':Math.min(party.members.length+1,3)}:undefined}>
 <PlayerSpot player={me} label="YOU · PARTY LEADER"/>
 {party?party.members.map(({player,status})=><div className="party-member" key={player.id}><PlayerSpot player={player} label={status==='pending'?'INVITE PENDING':'YOUR TEAMMATE'} pending={status==='pending'}/>{status==='pending'&&<div className="member-invite"><PartyDetails settings={party.settings}/><button className="secondary" onClick={()=>acceptInvite(player.id)}>Simulate accepting invite <Check size={15}/></button></div>}</div>):<><div className="party-center"><span className="party-plus"><Plus/></span><span>BETTER TOGETHER</span></div><div className="invite-spot"><div className="invite-circle"><Users size={40}/></div><h2>Room for your whole squad.</h2><p>Choose your players and set the plan before inviting.</p><button className="primary" onClick={openParty}>Create a party <Plus size={16}/></button></div></>}
 </div>
 {party&&<><p className="party-demo-note">Demo mode · invitations are simulated; no real invite is sent.</p><div className="game-setup"><h2>Your next sidequest: {party.settings.game}</h2><p>{party.members.some(m=>m.status==='pending')?'Waiting for everyone to join. Your game details are on every invite.':'Your squad is here. Add each other in game and get ready.'}</p><div className="ign-row squad-igns">{[me,...party.members.filter(m=>m.status==='joined').map(m=>m.player)].map(p=><div key={p.handle}><span>{p.name.split(' ')[0]}’s IGN · {party.settings.game}</span><strong>{p.ign}</strong><button aria-label={`Copy ${p.name}'s IGN`} onClick={async()=>{try{await navigator.clipboard.writeText(p.ign);setToast('IGN copied')}catch{setToast(`IGN: ${p.ign}`)}}}><Copy size={16}/></button></div>)}</div><button className="primary ready-button" disabled={party.members.some(m=>m.status==='pending')} onClick={()=>setReady(!ready)}>{ready?<CheckCheck size={20}/>:<Gamepad2 size={20}/>} {ready?'You’re ready! Click to unready':'We’ve added each other — ready up'}</button>{ready&&<p className="ready-note">You’re all set. Launch {party.settings.game} and enjoy your sidequest!</p>}</div></>}
 </section>:<ProfileView key={(selected||me).handle} player={selected||me} own={!selected} onBack={()=>setSelected(null)} onEdit={()=>setModal('edit')} onInvite={()=>invite(selected)} connected={selected&&friendIds.includes(selected.id)} onConnect={()=>connect(selected)} connections={people.filter(p=>friendIds.includes(p.id))} onDisconnect={disconnect} />}</main>
 <nav className="bottom-nav" aria-label="Main navigation">{[['Connect',Users],['Map',MapPin],['Play',Gamepad2],['Profile',User]].map(([t,Icon])=><button key={t} aria-current={tab===t?'page':undefined} className={'nav-item '+(t==='Play'?'nav-play ':'')+(tab===t?'nav-active':'')} onClick={()=>switchTab(t)}><span><Icon size={t==='Play'?29:22}/></span><strong>{t}</strong></button>)}</nav>
 {toast&&<div className="toast" role="status"><Check size={17}/>{toast}</div>}
 {modal&&<div className="modal-backdrop" onClick={()=>setModal(null)}><div className={"modal "+(modal==='party'?'party-modal':'')} role="dialog" aria-modal="true" aria-label={modal==='edit'?'Edit profile':modal==='interests'?'Choose your games':(party?'Manage party':'Create a party')} ref={dialogRef} onClick={e=>e.stopPropagation()}><button className="modal-close" aria-label="Close dialog" onClick={()=>setModal(null)}><X size={22}/></button>{modal==='interests'?<InterestEditor me={me} onSave={g=>{setMe({...me,games:g});setFilter('All games');setOnboard(false);localStorage.setItem('sq-onboarded','true');setModal(null);setToast('Your rotation is updated. Let’s find your people.')}}/>:modal==='edit'?<EditProfile me={me} onSave={p=>{setMe(p);setModal(null);setToast('Profile updated!')}}/>:<PartyEditor me={me} party={party} candidate={inviteCandidate} onSave={saveParty}/>}</div></div>}
 </div>
}
function PlayerSpot({player,label,pending=false}){return <div className="player-spot"><span className="eyebrow">{label}</span><img src={player.image} alt={player.name}/><h2>{player.name}</h2><p>@{player.handle}</p><span className={"player-connected "+(pending?"player-pending":"")}><span className="online-dot"/> {pending?"Invited":"Connected"}</span></div>}
function PartyDetails({settings}){
 return <div className="party-details"><span>{settings.game}</span><span>{settings.region} · {settings.style}</span>{settings.note&&<p>{settings.note}</p>}</div>
}
function PartyEditor({me,party,candidate,onSave}){
 const [settings,setSettings]=useState(()=>({game:party?.settings.game||me.games[0]||games[0],region:party?.settings.region||me.region,style:party?.settings.style||me.style,note:party?.settings.note||''}));
 const [chosen,setChosen]=useState(()=>[...(candidate&&!party?.members.some(m=>m.player.id===candidate.id)?[candidate.id]:[]),...(party?.members.map(m=>m.player.id)||[])]);
 const [query,setQuery]=useState('');
 const pickerRef=useRef(null);
 const update=(key,value)=>setSettings(current=>({...current,[key]:value}));
 const toggle=id=>{setChosen(current=>current.includes(id)?current.filter(x=>x!==id):current.length<5?[id,...current]:current);pickerRef.current?.scrollTo({top:0,behavior:'smooth'})};
 const matches=people.filter(p=>chosen.includes(p.id)||`${p.name} ${p.games.join(' ')}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>{const ai=chosen.indexOf(a.id),bi=chosen.indexOf(b.id);return ai>=0&&bi>=0?ai-bi:ai>=0?-1:bi>=0?1:a.id-b.id});
 return <form className="compact-party-form" onSubmit={e=>{e.preventDefault();if(chosen.length>5)return;onSave({settings:{...settings,note:settings.note.trim()},members:chosen.map(id=>party?.members.find(m=>m.player.id===id)||{player:people.find(p=>p.id===id),status:'pending'})})}}>
 <div className="eyebrow">BUILD YOUR PARTY</div><h2>{party?'Manage your party.':'Create a party.'}</h2>
 <div className="form-fields party-settings"><label>Game<select value={settings.game} onChange={e=>update('game',e.target.value)}>{games.map(g=><option key={g}>{g}</option>)}</select></label><label>Region<select value={settings.region} onChange={e=>update('region',e.target.value)}>{['North America','Europe','Asia','Oceania','South America'].map(r=><option key={r}>{r}</option>)}</select></label><label>Playstyle<select value={settings.style} onChange={e=>update('style',e.target.value)}><option>Casual</option><option>Competitive</option></select></label><label className="full-width">Session note (optional)<input maxLength={240} placeholder="Start time, server, or anything your squad should know" value={settings.note} onChange={e=>update('note',e.target.value)}/></label></div>
 <div className="party-picker-heading"><h3>Invite players <span aria-live="polite">{chosen.length+1} / 6</span></h3><label className="search party-search"><Search size={15}/><input aria-label="Search party players" placeholder="Search players or games" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>
 <div className="selected-squad"><span>{me.name.split(' ')[0]} · You</span>{chosen.map(id=><button type="button" key={id} onClick={()=>toggle(id)} aria-label={`Remove ${people[id].name}`}>{people[id].name.split(' ')[0]}<X size={12}/></button>)}</div>
 {chosen.length===5&&<p className="party-limit" role="status">Party full. Remove a player to choose someone else.</p>}
 <div className="invite-list party-picker" ref={pickerRef}>{matches.map(p=><button type="button" key={p.id} aria-pressed={chosen.includes(p.id)} disabled={!chosen.includes(p.id)&&chosen.length===5} className={chosen.includes(p.id)?'chosen':''} onClick={()=>toggle(p.id)}><div className="invite-player-photo"><img src={p.image} alt=""/><span className="invite-selection-icon">{chosen.includes(p.id)?<Check size={16}/>:<Plus size={16}/>}</span></div><span className="invite-player-info"><strong>{p.name}</strong><small>{p.games.includes(settings.game)?settings.game:p.games[0]} · {p.online?'Online':'Away'}</small></span></button>)}{!matches.length&&<p className="party-limit">No players found. Try another name or game.</p>}</div>
 <div className="party-editor-footer"><p className="party-demo-note">Demo invites · no real invitations sent.</p><button className="primary">{party?'Save party':`Create party${chosen.length?' & invite '+chosen.length:''}`}<ArrowRight size={16}/></button></div>
 </form>
}
function ConnectButton({connected,onConnect,name}){return <button type="button" className={'connect-player-button'+(connected?' is-connected':'')} disabled={connected} aria-label={connected?`Connected with ${name}`:`Connect with ${name}`} onClick={onConnect}>{connected?<Check size={15}/>:<UserPlus size={15}/>} {connected?'Connected':'Connect'}</button>}
function ProfileView({player,own,onBack,onEdit,onInvite,connected,onConnect,connections=[],onDisconnect}){
 const [section,setSection]=useState('Services'),[activeGame,setActiveGame]=useState(player.games[0]),[query,setQuery]=useState(''),[sort,setSort]=useState('Default'),[copied,setCopied]=useState(false),[menu,setMenu]=useState(false);
 useEffect(()=>{setSection('Services');setActiveGame(player.games[0]);setQuery('');setMenu(false)},[player.handle,player.games.join('|')]);
 const list=player.games.filter(g=>g.toLowerCase().includes(query.toLowerCase())).slice().sort((a,b)=>sort==='A–Z'?a.localeCompare(b):0);
 const game=player.games.includes(activeGame)?activeGame:player.games[0];
 const copyIgn=async()=>{try{await navigator.clipboard.writeText(player.ign);setCopied(true);setTimeout(()=>setCopied(false),2500)}catch{setMenu(true)}};
 return <section className="reference-profile">
 <div className="profile-cover"><img src={player.backgroundImage || playerImages[0].backgroundImage} alt=""/><div className="profile-cover-shade"/>{!own&&<button className="profile-back" onClick={onBack}><ArrowLeft size={16}/> Back to profiles</button>}
 <div className="profile-identity"><FramedAvatar player={player} large/><div className="profile-identity-copy"><h1>{player.name}</h1><LocationLabel location={player.location}/>{!own&&<ConnectButton connected={connected} onConnect={onConnect} name={player.name}/>}<p>@{player.handle} · {player.region} · English</p><div className="profile-badges"><span><span className="online-dot"/>{player.online?'Online':'Away'}</span><span className="vip-badge">✦ Player</span><span><Trophy size={13}/> {playerRank(player)}</span><span><Gamepad2 size={14}/> {player.games.length} games</span></div></div>
 <div className="profile-header-actions"><div className="profile-menu-wrap"><button className="round-action" aria-label="More profile options" aria-expanded={menu} onClick={()=>setMenu(!menu)}><MoreHorizontal size={23}/></button>{menu&&<div className="profile-options"><strong>@{player.handle}</strong><span>IGN: {player.ign}</span><button onClick={copyIgn}>{copied?'Copied!':'Copy in-game name'}</button></div>}</div><button className="round-action" aria-label={own?'Edit profile':'Plan a party'} onClick={own?onEdit:onInvite}><CalendarDays size={21}/></button><button className="round-action" aria-label="Copy in-game name" onClick={copyIgn}>{copied?<Check size={20}/>:<Copy size={20}/>}</button><button className="profile-main-action" onClick={own?onEdit:onInvite}>{own?'Edit profile':'Invite to party'}</button></div></div></div>
 <div className="profile-tabbar" role="tablist" aria-label="Profile sections">{['Achievement','Services',...(own?['Connections']:[]),'Album','Feeds','Wish'].map(t=><button key={t} role="tab" aria-selected={section===t} onClick={()=>setSection(t)}>{t}</button>)}</div>
 <div className="profile-tab-content" role="tabpanel" aria-label={section}>
 {section==='Services'?<><div className="service-toolbar"><label className="search"><Search size={16}/><input aria-label="Search profile games" placeholder="Search" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Sort profile games" value={sort} onChange={e=>setSort(e.target.value)}><option>Default</option><option>A–Z</option></select></div><div className="service-strip">{list.map((g,i)=><button key={g} className={'service-card '+(g===game?'selected':'')} aria-pressed={g===game} onClick={()=>setActiveGame(g)}><div className={'service-art service-art-'+games.indexOf(g)}><Gamepad2 size={36}/><strong>{g}</strong></div><strong className="service-name">{g}</strong><span className="service-meta"><span className="energy-token"><Zap size={10} fill="currentColor"/></span> Play together</span></button>)}{!list.length&&<p className="service-empty">No matching games.</p>}</div>
 {game?<div className="service-layout"><article className="service-description"><div className="service-description-head"><h2>{game}</h2><button className="service-invite" aria-label={own?'Edit game interests':'Invite to play '+game} onClick={own?onEdit:onInvite}><PlayIcon size={21} fill="currentColor"/></button></div><div className="service-rating"><Star size={16} fill="currentColor"/><strong>{player.style} · {player.online?'Ready to play':'Currently away'}</strong></div><p className="service-bio">{player.bio}</p><dl className="service-facts"><div><dt>Rank</dt><dd>{playerRank(player)}</dd></div><div><dt>Servers</dt><dd>{player.region==='North America'?'NA':player.region==='Europe'?'EU':player.region}</dd></div><div><dt>Styles</dt><dd>{player.style} / Good company / Team play</dd></div><div><dt>Platforms</dt><dd>PC</dd></div><div><dt>Positions</dt><dd>{playerRole(player)}</dd></div></dl><div className="service-feature-art"><Gamepad2 size={68}/><span>YOUR NEXT<br/><strong>{game.toUpperCase()}</strong><br/>SIDEQUEST</span></div></article><aside className="service-options"><img src={player.image} alt={player.name}/><h2>Play Types · 3</h2>{['Casual queues','Competitive games','Custom lobby'].map(t=><button key={t} onClick={own?onEdit:onInvite}><strong>{t}</strong><span><span className="energy-token"><Zap size={10} fill="currentColor"/></span>{own?'Edit your player card':'Invite to party'}</span></button>)}</aside></div>:<div className="profile-content-panel"><h2>No games yet</h2><p>Add games to your profile to find your next teammate.</p>{own&&<button className="primary" onClick={onEdit}>Edit profile</button>}</div>}</>:
 section==='Connections'&&own?<div className="profile-content-panel profile-connections"><Users size={30}/><h2>Connections <span>{connections.length}</span></h2><p>Your people, all in one place.</p>{connections.length?<ul className="profile-connections-list">{connections.map(person=><li key={person.id}><img src={person.image} alt=""/><div className="profile-connection-info"><strong>{person.name}</strong><span>@{person.handle}</span><LocationLabel location={person.location}/></div><button type="button" className="remove-connection" aria-label={`Remove ${person.name} from connections`} onClick={()=>onDisconnect(person)}><X size={15}/> Remove</button></li>)}</ul>:<div className="profile-connections-empty"><UserPlus size={26}/><h3>No connections yet</h3><p>Connect with players from the Connect view to see them here.</p></div>}</div>:
 section==='Achievement'?<div className="profile-content-panel"><Trophy size={32}/><h2>Player achievements</h2><div className="achievement-grid"><div><strong>{playerRank(player)}</strong><span>Player rank</span></div><div><strong>{player.games.length}</strong><span>Games in the rotation</span></div><div><strong>{playerRole(player)}</strong><span>Preferred role</span></div></div></div>:
 section==='Album'?<div className="profile-content-panel"><h2>Album</h2><img className="album-photo" src={player.image} alt={player.name}/></div>:
 section==='Feeds'?<div className="profile-content-panel"><h2>A little about {own?'me':player.name.split(' ')[0]}</h2><p>{player.bio}</p><span className="profile-content-muted">No posts yet.</span></div>:
 <div className="profile-content-panel"><Heart size={30}/><h2>Wish</h2><p>Looking for good company in {player.games.join(', ')}.</p>{!own&&<button className="primary" onClick={onInvite}>Invite to party <UserPlus size={16}/></button>}</div>}
 </div></section>
}
function InterestEditor({me,onSave}){const [chosen,setChosen]=useState(me.games);return <><div className="eyebrow">LET’S FIND YOUR PEOPLE</div><h2>What’s in your rotation?</h2><p>Pick the games you love. We’ll handle the introductions.</p><div className="interest-options">{games.map(g=><button className={chosen.includes(g)?'selected':''} key={g} onClick={()=>setChosen(chosen.includes(g)?chosen.filter(x=>x!==g):[...chosen,g])}><Gamepad2 size={20}/>{g}{chosen.includes(g)?<Check size={18}/>:<Plus size={18}/>}</button>)}</div><button className="primary modal-save" disabled={!chosen.length} onClick={()=>onSave(chosen)}>Save my games <ArrowRight size={17}/></button></>}
function EditProfile({me,onSave}){const [draft,setDraft]=useState({...me}),[error,setError]=useState('');const update=(key,value)=>setDraft(current=>({...current,[key]:value}));return <form onSubmit={e=>{e.preventDefault();if(!isValidLocation(draft.location))return;onSave(draft)}}><div className="eyebrow">MAKE IT YOURS</div><h2>Edit your player card.</h2><label className="photo-upload"><img src={draft.image} alt="Profile preview"/><span><Camera size={18}/> Change photo</span><input type="file" accept="image/*" onChange={e=>{const f=e.target.files[0];if(!f)return;if(f.size>3000000){setError('Choose an image under 3 MB.');return}const r=new FileReader();r.onload=()=>update('image',r.result);r.readAsDataURL(f)}}/></label>{error&&<p>{error}</p>}<div className="form-fields"><LocationPicker location={draft.location} onChange={value=>update('location',value)}/><label>Name<input required maxLength={35} value={draft.name} onChange={e=>update('name',e.target.value)}/></label><label>Username<input required maxLength={25} value={draft.handle} onChange={e=>update('handle',e.target.value)}/></label><label className="full-width">About you<textarea maxLength={350} value={draft.bio} onChange={e=>update('bio',e.target.value)}/></label><label>In-game name<input required value={draft.ign} onChange={e=>update('ign',e.target.value)}/></label><label>Region<select value={draft.region} onChange={e=>update('region',e.target.value)}><option>North America</option><option>Europe</option><option>Asia</option><option>Oceania</option><option>South America</option></select></label><label>Playstyle<select value={draft.style} onChange={e=>update('style',e.target.value)}><option>Casual</option><option>Competitive</option></select></label></div><h4>Your games</h4><div className="edit-game-chips">{games.map(g=><button type="button" key={g} className={draft.games.includes(g)?'chosen':''} onClick={()=>update('games',draft.games.includes(g)?draft.games.filter(x=>x!==g):[...draft.games,g])}>{g}</button>)}</div><button className="primary modal-save" disabled={!draft.games.length||!isValidLocation(draft.location)}>Save profile <Check size={17}/></button></form>}
createRoot(document.getElementById('root')).render(<App/>);
